sudo: required
dist: focal
language: node_js
node_js:
  - "14"

git:
  depth: false

cache:
  yarn: true

before_install:
  - sudo apt-get update
  - sudo apt-get install python2

install:
  - yarn

script:
  - yarn start:ganache > /dev/null &
  - sleep 5
  - yarn build
  - yarn start
  - yarn test